// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:362784193588:web:25a204202b74e67dab5e61',
    messagingSenderId: '362784193588',
    projectId: 'kind-kart-5454',
    authDomain: 'kind-kart-5454.firebaseapp.com',
    storageBucket: 'kind-kart-5454.firebasestorage.app',
    measurementId: 'G-MSQQN4NF0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:362784193588:android:70d4140a696b46d8ab5e61',
    messagingSenderId: '362784193588',
    projectId: 'kind-kart-5454',
    storageBucket: 'kind-kart-5454.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:362784193588:ios:83cd90d57fc1e226ab5e61',
    messagingSenderId: '362784193588',
    projectId: 'kind-kart-5454',
    storageBucket: 'kind-kart-5454.firebasestorage.app',
    iosBundleId: 'com.example.kindKartNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:362784193588:ios:83cd90d57fc1e226ab5e61',
    messagingSenderId: '362784193588',
    projectId: 'kind-kart-5454',
    storageBucket: 'kind-kart-5454.firebasestorage.app',
    iosBundleId: 'com.example.kindKartNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:362784193588:web:edc3da06bdfcb2deab5e61',
    messagingSenderId: '362784193588',
    projectId: 'kind-kart-5454',
    authDomain: 'kind-kart-5454.firebaseapp.com',
    storageBucket: 'kind-kart-5454.firebasestorage.app',
    measurementId: 'G-7T86FFGRGR',
  );

}
